#!/usr/bin/python
#-*-encoding:utf-8 -*-
import os
from os.path import join,getsize

def get_dir_size(dir):
    size = 0
    for root,dirs,files in os.walk(dir):
        size += sum([getsize(join(root,name)) for name in files])
    return size
    
if __name__ == '__main__':
    for dir_list in os.listdir("c:\\")[3:]:
        path = ('c:\\' + dir_list)
        filesize = get_dir_size(path)
        print('There are %.3f' % (filesize/1024/1024), 'Mbytes in %s' %dir_list)
