#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from bs4 import BeautifulSoup as bs
import requests
import os
import time
import random


class mzitu():

    def __init__(self):
        self.headers = {
            'User-Agent':'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0'
        }

    def all_url(self,url):
        #调用requests函数吧套图地址穿进去会返回给我们response
        html = self.request(url)
        i = 1130
        all_a = bs(html.text, 'lxml').find('div', class_='all').find_all('a')[1130:]
        # print(all_a)
        # print(type(all_a))
        for a in all_a:
            title = a.get_text()
            print(i,u'开始保存:',title)
            path = str(title).replace("?","_").replace(":","_")
            self.mkdir(path)
            href = a['href']
            i += 1
            self.html(href)

    def html(self,href):

        html = self.request(href)
        self.headers['referer'] = href
        max_span = bs(html.text,'lxml').find('div', class_='pagenavi').find_all('span')[-2].get_text()
        for page in range(1,int(max_span)+1):
            page_url = href + '/' + str(page)
            self.img(page_url)

    def img(self,page_url):
        img_html = self.request(page_url)
        img_url = bs(img_html.text,'lxml').find('div', class_='main-image').find('img')['src']
        self.save(img_url)

    def save(self,img_url):
        # name = img_url[-9:-4]
        name = img_url.split('/')[-1]
        img = self.request(img_url)
        # f = open(name + '.jpg','ab')
        f = open(name,'ab')
        f.write(img.content)
        f.close()

    def mkdir(self,path):
        path = path.strip()
        isExists = os.path.exists(os.path.join("D:\\ostext\meizitu\\",path))
        if not isExists:
            print(u'建了一个名字叫做:',path,u'的文件夹')
            os.makedirs(os.path.join("D:\\ostext\meizitu\\",path))
            os.chdir(os.path.join("D:\\ostext\meizitu\\",path))
            return True
        else:
            print(u'名字叫做:',path,u'的文件夹已经存在')
            return False


    def request(self,url):
        content = requests.get(url,headers = self.headers)
        # print(content.text)
        # time.sleep(int(random.randint(1,3)))
        return content

Mzitu = mzitu()
Mzitu.all_url('http://www.mzitu.com/all')
